---
# handlers file for webserver
- name: Restart Httpd
  service: 
    name: httpd
    state: restarted

- name: Restart Httpd
  service: 
    name: apache2
    state: restarted

- name: Reload Apache
  service: 
    name: apache2
    state: reloaded

- name: Restart Apache
  service:
    name: apache2
    state: restarted